name: Bug
description: Reportar un error o comportamiento incorrecto del sistema.
title: "[BUG] "
labels: ["type: bug"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      description: Qué pasó y qué esperabas que pasara.
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      placeholder: |
        1. Ir a...
        2. Hacer clic en...
        3. Ver el error
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Comportamiento esperado
    validations:
      required: false
  - type: dropdown
    id: modulo
    attributes:
      label: Módulo
      options:
        - Configuración
        - Seguridad
        - Profesionales
        - Pacientes
        - Turnos
        - Agenda
        - Atención
        - Pagos
        - Indicadores
        - Autogestión
    validations:
      required: false
  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      options:
        - Alta
        - Media
        - Baja
    validations:
      required: true
