name: Task
description: Tarea técnica que no corresponde a una Historia de Usuario ni a un bug.
title: "[TASK] "
labels: ["type: task"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      description: Qué hay que hacer y por qué.
    validations:
      required: true
  - type: dropdown
    id: modulo
    attributes:
      label: Módulo
      options:
        - Configuración
        - Seguridad
        - Profesionales
        - Pacientes
        - Turnos
        - Agenda
        - Atención
        - Pagos
        - Indicadores
        - Autogestión
    validations:
      required: false
  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      options:
        - Alta
        - Media
        - Baja
    validations:
      required: true
